import type { GaugeDesignConfig, GaugePlatformInstance } from "@/widget-platform/types";

export type GaugeGalleryPresetMeta = {
  id: string;
  label: string;
  description: string;
  design: GaugeDesignConfig;
  format?: GaugePlatformInstance["format"];
  defaultMin: number;
  defaultMax: number;
};

/** All 16 react-gauge-component gallery presets (serializable designs for platform merge). */
export const GAUGE_GALLERY_CATALOG: GaugeGalleryPresetMeta[] = [
  {
    id: "server-temperature",
    label: "Server Temperature",
    description: "Datacenter monitoring with zones",
    defaultMin: 10,
    defaultMax: 50,
    format: { unit: "°C", decimals: 1 },
    design: {
      gaugeType: "semicircle",
      minValue: 10,
      maxValue: 50,
      arc: {
        width: 0.2,
        padding: 0.015,
        cornerRadius: 2,
        subArcs: [
          { limit: 18, color: "#00bcd4", showTick: true },
          { limit: 25, color: "#4caf50", showTick: true },
          { limit: 35, color: "#ff9800", showTick: true },
          { color: "#f44336" },
        ],
      },
      pointer: { type: "needle", color: "#e0e0e0", length: 0.7, width: 8 },
      labels: {
        valueLabel: { fontSize: "20px", matchColorWithArc: false },
        tickLabels: { type: "outer", tickValues: [10, 18, 25, 35, 50] },
      },
    },
  },
  {
    id: "network-speed",
    label: "Network Speed",
    description: "Bandwidth meter with formatted values",
    defaultMin: 0,
    defaultMax: 3000,
    design: {
      gaugeType: "semicircle",
      minValue: 0,
      maxValue: 3000,
      arc: {
        nbSubArcs: 150,
        colorArray: ["#5BE12C", "#F5CD19", "#EA4228"],
        width: 0.3,
        padding: 0.003,
        cornerRadius: 0,
      },
      pointer: { type: "needle", length: 0.75, width: 8 },
      labels: {
        valueLabel: { fontSize: "40px", offsetY: -20 },
        tickLabels: {
          type: "outer",
          tickValues: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 2500, 3000],
        },
      },
    },
  },
  {
    id: "grafana-neon",
    label: "Grafana Neon",
    description: "Grafana with neon glow effect",
    defaultMin: 0,
    defaultMax: 1000,
    design: {
      gaugeType: "grafana",
      minValue: 0,
      maxValue: 1000,
      arc: {
        width: 0.55,
        cornerRadius: 0,
        nbSubArcs: 52,
        colorArray: ["#ff00ff", "#00ffff", "#ffff00", "#ff0080"],
        padding: 0,
        subArcsStrokeWidth: 1,
        subArcsStrokeColor: "#000000",
        effects: { glow: true, glowBlur: 1, glowSpread: 2 },
      },
      pointer: {
        type: "needle",
        elastic: true,
        animationDelay: 50,
        animationDuration: 3000,
        length: 0.87,
        width: 24,
        baseColor: "#ffffff",
        strokeWidth: 2,
        strokeColor: "#000000",
      },
      labels: {
        valueLabel: { fontSize: "29px", matchColorWithArc: true, offsetY: 25 },
        tickLabels: { type: "outer", tickValues: [0, 250, 500, 1000] },
      },
    },
  },
  {
    id: "custom-angle",
    label: "Custom Angle",
    description: "Custom angle radial with neon colors",
    defaultMin: -300,
    defaultMax: 3000,
    design: {
      gaugeType: "radial",
      minValue: -300,
      maxValue: 3000,
      startAngle: -145,
      endAngle: 40,
      arc: {
        width: 0.55,
        cornerRadius: 0,
        nbSubArcs: 52,
        colorArray: ["#ff00ff", "#00ffff", "#ffff00", "#ff0080"],
        padding: 0,
        subArcsStrokeWidth: 1,
        subArcsStrokeColor: "#000000",
        effects: { glow: true, glowBlur: 13, glowSpread: 0.2 },
      },
      pointer: {
        type: "needle",
        elastic: true,
        animationDelay: 200,
        animationDuration: 3000,
        length: 0.87,
        width: 24,
        baseColor: "#ffffff",
        strokeWidth: 2,
        strokeColor: "#000000",
      },
      labels: {
        valueLabel: { fontSize: "29px", matchColorWithArc: true, offsetY: -6 },
        tickLabels: { type: "outer", tickValues: [0, 2000, 3000] },
      },
    },
  },
  {
    id: "green-speedometer",
    label: "Green Speedometer",
    description: "Neon green arc with km/h ticks",
    defaultMin: 0,
    defaultMax: 180,
    format: { unit: "km/h", decimals: 0 },
    design: {
      gaugeType: "semicircle",
      minValue: 0,
      maxValue: 180,
      arc: {
        width: 0.08,
        cornerRadius: 0,
        padding: 0,
        subArcs: [{ color: "#00ff41" }],
        effects: { glow: true, glowBlur: 15, glowSpread: 1 },
      },
      pointer: {
        type: "needle",
        color: "#ff3300",
        length: 0.85,
        width: 4,
        baseColor: "#1a1a1a",
      },
      labels: {
        valueLabel: { fontSize: "18px" },
        tickLabels: {
          type: "outer",
          tickValues: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180],
        },
      },
    },
  },
  {
    id: "battery",
    label: "Battery",
    description: "Battery level with color zones",
    defaultMin: 0,
    defaultMax: 100,
    format: { unit: "%", decimals: 0 },
    design: {
      gaugeType: "grafana",
      minValue: 0,
      maxValue: 100,
      arc: {
        width: 0.25,
        padding: 0.02,
        subArcs: [
          { limit: 20, color: "#EA4228", showTick: true },
          { limit: 40, color: "#F58B19", showTick: true },
          { limit: 60, color: "#F5CD19", showTick: true },
          { limit: 100, color: "#5BE12C", showTick: true },
        ],
      },
      pointer: { type: "arrow", color: "#e0e0e0", width: 15 },
      labels: {
        valueLabel: { matchColorWithArc: true },
        tickLabels: { type: "outer" },
      },
    },
  },
  {
    id: "fuel-gauge",
    label: "Fuel Gauge",
    description: "Classic E/F fuel indicator",
    defaultMin: 0,
    defaultMax: 100,
    design: {
      gaugeType: "semicircle",
      minValue: 0,
      maxValue: 100,
      arc: {
        width: 0.18,
        subArcs: [{ limit: 25, color: "#EA4228" }, { color: "#5BE12C" }],
      },
      pointer: { type: "arrow", color: "#e0e0e0", width: 20 },
      labels: {
        valueLabel: { fontSize: "22px" },
        tickLabels: { type: "outer", tickValues: [0, 50, 100] },
      },
    },
  },
  {
    id: "warm-glow",
    label: "Warm Glow",
    description: "Warm colors with glow effect",
    defaultMin: 0,
    defaultMax: 1,
    design: {
      gaugeType: "semicircle",
      minValue: 0,
      maxValue: 1,
      arc: {
        width: 1,
        cornerRadius: 44,
        nbSubArcs: 12,
        colorArray: ["#ff6b35", "#f7931e", "#ffcc02", "#ff3d00"],
        padding: 0.02,
        subArcsStrokeWidth: 1,
        subArcsStrokeColor: "#5e5c64",
        effects: {
          glow: true,
          glowSpread: 0.3,
          glowBlur: 11,
          dropShadow: { dy: 2, blur: 9, opacity: 0.6 },
        },
      },
      pointer: {
        type: "needle",
        baseColor: "#9a9996",
        strokeWidth: 1,
        strokeColor: "#5e5c64",
      },
      labels: {
        valueLabel: { fontSize: "40px", matchColorWithArc: true },
        tickLabels: { type: "outer", tickValues: [0, 0.5, 1] },
      },
    },
  },
  {
    id: "frost-crystal",
    label: "Frost Crystal",
    description: "Icy winter theme",
    defaultMin: 0,
    defaultMax: 100,
    format: { unit: "%", decimals: 2 },
    design: {
      gaugeType: "grafana",
      minValue: 0,
      maxValue: 100,
      arc: {
        width: 0.25,
        padding: 0.01,
        subArcs: [
          { limit: 33, color: "#e0f7fa" },
          { limit: 66, color: "#80deea" },
          { color: "#00bcd4" },
        ],
        effects: { glow: true, glowBlur: 15, glowSpread: 0.5 },
      },
      pointer: { type: "needle", color: "#fff", length: 0.8, width: 6 },
      labels: {
        valueLabel: { fontSize: "26px" },
        tickLabels: { type: "outer", hideMinMax: true },
      },
    },
  },
  {
    id: "uv-index",
    label: "UV Index",
    description: "Sun exposure with risk levels",
    defaultMin: 0,
    defaultMax: 11,
    design: {
      gaugeType: "grafana",
      minValue: 0,
      maxValue: 11,
      arc: {
        width: 0.3,
        padding: 0.015,
        subArcs: [
          { limit: 3, color: "#4caf50" },
          { limit: 6, color: "#ffeb3b" },
          { limit: 8, color: "#ff9800" },
          { limit: 10, color: "#f44336" },
          { color: "#9c27b0" },
        ],
      },
      pointer: { type: "needle", color: "#fff", length: 0.75, width: 10 },
      labels: {
        valueLabel: { fontSize: "20px", matchColorWithArc: true },
        tickLabels: { type: "outer", tickValues: [0, 3, 6, 8, 11] },
      },
    },
  },
  {
    id: "sound-level",
    label: "Sound Level",
    description: "Decibel meter with VU style",
    defaultMin: 0,
    defaultMax: 120,
    format: { unit: "dB", decimals: 0 },
    design: {
      gaugeType: "semicircle",
      minValue: 0,
      maxValue: 120,
      arc: {
        width: 0.15,
        padding: 0.008,
        nbSubArcs: 24,
        colorArray: [
          "#00c853",
          "#00c853",
          "#76ff03",
          "#c6ff00",
          "#ffea00",
          "#ffc400",
          "#ff9100",
          "#ff3d00",
          "#dd2c00",
        ],
      },
      pointer: {
        type: "needle",
        color: "#111",
        length: 0.8,
        width: 4,
        baseColor: "#333",
      },
      labels: {
        valueLabel: { fontSize: "22px" },
        tickLabels: { type: "outer", tickValues: [0, 40, 70, 85, 120] },
      },
    },
  },
  {
    id: "compass-bearing",
    label: "Compass Bearing",
    description: "Navigation heading indicator",
    defaultMin: 0,
    defaultMax: 360,
    format: { unit: "°", decimals: 0 },
    design: {
      gaugeType: "radial",
      minValue: 0,
      maxValue: 360,
      startAngle: -180,
      endAngle: 180,
      arc: { width: 0.08, cornerRadius: 0, subArcs: [{ color: "#3498db" }] },
      pointer: { type: "needle", color: "#e74c3c", length: 0.7, width: 6 },
      labels: {
        valueLabel: { fontSize: "18px" },
        tickLabels: { type: "outer", hideMinMax: true, tickValues: [0, 90, 180, 270] },
      },
    },
  },
  {
    id: "humidity-meter",
    label: "Humidity Meter",
    description: "Moisture level indicator",
    defaultMin: 0,
    defaultMax: 100,
    format: { unit: "% RH", decimals: 0 },
    design: {
      gaugeType: "grafana",
      minValue: 0,
      maxValue: 100,
      arc: {
        width: 0.25,
        subArcs: [
          { limit: 30, color: "#ffcc80" },
          { limit: 60, color: "#4fc3f7" },
          { color: "#0277bd" },
        ],
      },
      pointer: { type: "blob", color: "#4fc3f7", elastic: true },
      labels: {
        valueLabel: { fontSize: "22px" },
        tickLabels: { type: "outer", tickValues: [0, 30, 60, 100] },
      },
    },
  },
  {
    id: "gradient-arrow",
    label: "Gradient Arrow",
    description: "Smooth gradient with arrow pointer",
    defaultMin: 0,
    defaultMax: 100,
    design: {
      gaugeType: "semicircle",
      minValue: 0,
      maxValue: 100,
      arc: {
        gradient: true,
        width: 0.15,
        padding: 0,
        subArcs: [
          { limit: 5, color: "#EA4228" },
          { limit: 20, color: "#F5CD19" },
          { limit: 58, color: "#5BE12C" },
          { limit: 75, color: "#F5CD19" },
          { color: "#EA4228" },
        ],
      },
      pointer: { type: "arrow", color: "#dfa810" },
      labels: {
        valueLabel: { fontSize: "24px" },
        tickLabels: { type: "outer", tickValues: [0, 20, 40, 60, 80, 100] },
      },
    },
  },
  {
    id: "radial-elastic",
    label: "Radial Elastic",
    description: "Bouncy needle animation",
    defaultMin: 0,
    defaultMax: 100,
    design: {
      gaugeType: "radial",
      minValue: 0,
      maxValue: 100,
      arc: {
        colorArray: ["#5BE12C", "#EA4228"],
        subArcs: [
          { limit: 10, color: "#5BE12C" },
          { limit: 30, color: "#EA4228" },
          { color: "#5BE12C" },
          { color: "#EA4228" },
          { color: "#5BE12C" },
        ],
        padding: 0.02,
        width: 0.3,
      },
      pointer: {
        type: "needle",
        color: "#e0e0e0",
        elastic: true,
        animationDelay: 0,
      },
      labels: {
        valueLabel: { fontSize: "36px" },
        tickLabels: { type: "inner", tickValues: [20, 40, 60, 80, 100] },
      },
    },
  },
  {
    id: "grafana-smooth",
    label: "Grafana Smooth",
    description: "Smooth color interpolation",
    defaultMin: 0,
    defaultMax: 100,
    design: {
      gaugeType: "grafana",
      minValue: 0,
      maxValue: 100,
      arc: {
        colorArray: ["#1EFF00", "#CE1F1F"],
        nbSubArcs: 80,
        padding: 0.02,
        width: 0.3,
      },
      pointer: { type: "needle", color: "#e0e0e0", animationDelay: 0 },
      labels: {
        valueLabel: { fontSize: "28px", matchColorWithArc: true },
        tickLabels: { type: "outer", hideMinMax: true },
      },
    },
  },
];

/** Dashboard Internet Speed widget — Mbps scale (not gallery kbit/s preset). */
export const DASHBOARD_SPEED_PRESET: GaugeGalleryPresetMeta = {
  id: "dashboard-network-speed",
  label: "Dashboard network speed",
  description: "Mbps scale for Internet Speed widget",
  defaultMin: 0,
  defaultMax: 500,
  format: { unit: "Mbps", decimals: 1 },
  design: {
    gaugeType: "semicircle",
    minValue: 0,
    maxValue: 500,
    arc: {
      nbSubArcs: 120,
      colorArray: ["#5BE12C", "#F5CD19", "#EA4228"],
      width: 0.28,
      padding: 0.003,
      cornerRadius: 0,
    },
    pointer: { type: "arrow", elastic: false, animationDuration: 400 },
    labels: {
      valueLabel: { fontSize: "clamp(0.8rem, 7cqmin, 1.35rem)" },
      tickLabels: { type: "outer", tickValues: [0, 100, 200, 300, 400, 500] },
    },
  },
};
