#!/bin/bash
# Generate a fresh .env with random passwords (no change_me placeholders).
# Usage: ./scripts/generate-env.sh [SERVER_IP]
# Package version: see VERSION at repo root.

set -e
cd "$(dirname "$0")/.."

SERVER_IP="${1:-}"
if [ -z "$SERVER_IP" ]; then
  SERVER_IP=$(hostname -I | awk '{print $1}')
fi
if [ -z "$SERVER_IP" ]; then
  echo "Error: could not detect server IP. Run: ./scripts/generate-env.sh YOUR_SERVER_IP"
  exit 1
fi

rand_hex() {
  openssl rand -hex 16
}

rand_hex_32() {
  openssl rand -hex 32
}

PG_PASS=$(rand_hex)
INFLUX_PASS=$(rand_hex)
INFLUX_TOKEN=$(rand_hex_32)
MQTT_PASS=$(rand_hex)
JWT_SECRET=$(rand_hex_32)
ADMIN_PASS=$(rand_hex)

cat > .env <<EOF
# Generated by scripts/generate-env.sh — $(date -Iseconds)
SERVER_IP=${SERVER_IP}

POSTGRES_USER=nexternel
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=nexternel
DATABASE_URL=postgresql://nexternel:${PG_PASS}@postgres:5432/nexternel

INFLUXDB_USER=admin
INFLUXDB_PASSWORD=${INFLUX_PASS}
INFLUXDB_ORG=nexternel
INFLUXDB_BUCKET=sensors
INFLUXDB_TOKEN=${INFLUX_TOKEN}
INFLUXDB_URL=http://influxdb:8086

MQTT_BROKER=mqtt://mosquitto:1883
MQTT_USERNAME=nexternel
MQTT_PASSWORD=${MQTT_PASS}
MQTT_TOPIC_PREFIX=nexternel

NEXTAUTH_SECRET=${JWT_SECRET}
UI_PORT=8080
API_PORT=4000

GO2RTC_URL=http://go2rtc:1984
GO2RTC_PORT=1984

ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASS}

TZ=Europe/London
EOF

chmod 600 .env 2>/dev/null || true

echo "Created .env with random passwords for server ${SERVER_IP}."
echo "Admin login: admin / (see ADMIN_PASSWORD in .env)"
echo "You do not need to remember MQTT or database passwords — Nexternel manages them."
