import {
  ESPHOME_BOARD_CATALOG,
  ESPHOME_BUILDER_CONFIG_VERSION,
  type BuilderComponent,
  type EsphomeBoardId,
  type EsphomeDeviceBuilderConfig,
  type EsphomePlatform,
} from "@nexternel/domain";
import {
  extractTopLevelSection,
  splitYamlListItems,
} from "../yaml.js";

const BUILDER_MARKER = "# Nexternel managed device";

function parsePin(block: string): number | undefined {
  const inline = /\bpin:\s*GPIO?(\d+)/i.exec(block);
  if (inline) return Number(inline[1]);
  return undefined;
}

function parseInterval(block: string): number | undefined {
  const m = /update_interval:\s*(\d+)s/i.exec(block);
  return m ? Number(m[1]) : undefined;
}

function boardIdFromEsphomeBoard(
  platform: EsphomePlatform,
  esphomeBoard: string
): EsphomeBoardId | null {
  const match = ESPHOME_BOARD_CATALOG.find(
    (b) => b.platform === platform && b.esphomeBoard === esphomeBoard
  );
  return match?.id ?? null;
}

function detectPlatform(yaml: string): {
  platform: EsphomePlatform;
  boardId: EsphomeBoardId;
} | null {
  const esp32 = /esp32:\s*\n\s*board:\s*(\S+)/m.exec(yaml);
  if (esp32) {
    const boardId = boardIdFromEsphomeBoard("esp32", esp32[1]);
    if (boardId) return { platform: "esp32", boardId };
  }
  const esp8266 = /esp8266:\s*\n\s*board:\s*(\S+)/m.exec(yaml);
  if (esp8266) {
    const boardId = boardIdFromEsphomeBoard("esp8266", esp8266[1]);
    if (boardId) return { platform: "esp8266", boardId };
  }
  return null;
}

function componentIdFromEntity(entityId: string, slug: string): string {
  const prefix = `${slug}_`;
  if (entityId.startsWith(prefix)) {
    return entityId.slice(prefix.length).replace(/_temperature$|_humidity$|_pm1$|_pm25$|_pm10$|_power$|_total$|_daily$/, "");
  }
  return entityId;
}

/**
 * Best-effort reverse parse of Device Builder YAML into builder config.
 * Only supports YAML generated by Nexternel (marker comment required).
 */
export function parseManagedBuilderConfigFromYaml(
  yaml: string,
  slug: string,
  displayNameFallback: string
): EsphomeDeviceBuilderConfig | null {
  if (!yaml.includes(BUILDER_MARKER)) return null;

  const platformInfo = detectPlatform(yaml);
  if (!platformInfo) return null;

  const friendly =
    /friendly_name:\s*["']?([^"'\n]+)/m.exec(yaml)?.[1]?.trim() ||
    /#\s*Device:\s*(.+)/m.exec(yaml)?.[1]?.trim() ||
    displayNameFallback;

  const components: BuilderComponent[] = [];
  const seen = new Set<string>();

  const sensorSection = extractTopLevelSection(yaml, "sensor");
  if (sensorSection) {
    for (const block of splitYamlListItems(sensorSection)) {
      const platform = /\bplatform:\s*([\w_]+)/i.exec(block)?.[1]?.toLowerCase();
      if (!platform) continue;

      if (platform === "dht") {
        const pin = parsePin(block);
        const variant = /\bmodel:\s*(\w+)/i.exec(block)?.[1] as
          | "DHT11"
          | "DHT22"
          | "DHT21"
          | undefined;
        const idM = /\bid:\s*([\w-]+)_temperature/i.exec(block);
        const compId = idM ? componentIdFromEntity(idM[1], slug) : `dht${components.length + 1}`;
        if (seen.has(compId) || pin === undefined || !variant) continue;
        seen.add(compId);
        components.push({
          id: compId,
          kind: "dht",
          variant,
          pin,
          updateIntervalSeconds: parseInterval(block),
        });
        continue;
      }

      if (platform === "pmsx003") {
        const uartSection = extractTopLevelSection(yaml, "uart");
        const uartBlock = uartSection ? splitYamlListItems(uartSection)[0] : "";
        const uartId = /\buart_id:\s*uart_(\w+)/i.exec(block)?.[1];
        const tx = uartBlock ? /\btx_pin:\s*GPIO?(\d+)/i.exec(uartBlock)?.[1] : undefined;
        const rx = uartBlock ? /\brx_pin:\s*GPIO?(\d+)/i.exec(uartBlock)?.[1] : undefined;
        const compId = uartId || `pms${components.length + 1}`;
        if (seen.has(compId) || !tx || !rx) continue;
        seen.add(compId);
        const variant = /\btype:\s*(\w+)/i.exec(block)?.[1] as
          | "PMSX003"
          | "PMS5003"
          | "PMS7003"
          | undefined;
        components.push({
          id: compId,
          kind: "pms",
          variant: variant || "PMSX003",
          uartTxPin: Number(tx),
          uartRxPin: Number(rx),
          updateIntervalSeconds: parseInterval(block),
        });
        continue;
      }

      if (platform === "pulse_meter") {
        const pin = parsePin(block);
        const idM = /\bid:\s*([\w-]+)_power/i.exec(block);
        const compId = idM ? componentIdFromEntity(idM[1], slug) : `energy${components.length + 1}`;
        const rateM = /\(60\.0\s*\/\s*(\d+)\)/.exec(block);
        if (seen.has(compId) || pin === undefined) continue;
        seen.add(compId);
        components.push({
          id: compId,
          kind: "pulse_meter",
          pin,
          pulseRate: rateM ? Number(rateM[1]) : 1000,
        });
      }
    }
  }

  const switchSection = extractTopLevelSection(yaml, "switch");
  if (switchSection) {
    for (const block of splitYamlListItems(switchSection)) {
      if (!/platform:\s*gpio/i.test(block)) continue;
      const pin = parsePin(block);
      const name = /\bname:\s*"([^"]+)"/i.exec(block)?.[1];
      const idM = /\bid:\s*([\w-]+)/i.exec(block);
      if (!pin || !name || !idM) continue;
      const compId = idM[1].startsWith(`${slug}_`)
        ? idM[1].slice(slug.length + 1)
        : idM[1];
      if (seen.has(compId)) continue;
      seen.add(compId);
      const inverted = /\binverted:\s*true/i.test(block);
      components.push({
        id: compId,
        kind: "gpio_switch",
        pin,
        name,
        inverted,
      });
    }
  }

  if (components.length === 0) return null;

  return {
    version: ESPHOME_BUILDER_CONFIG_VERSION,
    platform: platformInfo.platform,
    boardId: platformInfo.boardId,
    displayName: friendly,
    slug,
    components,
  };
}
